all:
	python3 test_hw4_1.py
	python3 test_hw4_2.py

test:
	python3 test_hw4_1.py
	python3 test_hw4_2.py

lint:
	pylint hw4_1.py hw4_2.py test_hw4_2.py

flake8:
	flake8 hw4_1.py hw4_2.py test_hw4_1.py test_hw4_2.py

clean: